### ISSUE TITLE
Chart utility research

### ISSUE THREAD

**Issue by jcmtallon** [power-guard/pg_monitor_dashboard#11]
## Description
- [ ] Research performant chart utility

**Comment by jcmtallon** [comment]
Notes regarding chart library: 

- Based on what I researched so far, there seems to be some agreement that canvas based chart libraries are more performant than svg based chart libraries when dealing with a large number of data objects. Not that this is the only factor to keep in mind when considering performance though. 
https://www.barchart.com/solutions/company/blog/3852318/comparing-html5-canvas-vs-svg-for-charting
https://cosaic.io/javascript-charting-libraries-html5-canvas-element-vs-svg/#:~:text=When%20we%20evaluated%20performance%2C%20we,time%20mathematical%20operations%20and%20animations.

- D3:  most extensively used library. Highlycustomizable. I have used it before in my other project todoNext. However learning curve is steep and development cost is high. Also, svg based. 

- Highcharts or ZingCharst  are very highly reviewed, thougth commercial license is required in our case, being strict. 

- Chart.js is canvas based, only 60k, open source and seems pretty intuitive. Not a large variety of charts, but it covers our user cases so far. Considering trying this one first.  Might end up testing 2 or 3 libraries to make sure we choose the right one.

**Comment by jcmtallon** [comment]
First stress tests with Chart.js looking promising. It's still early to jump into conclussions but, as they mention in the documentation, disabling animations, among other tips, might become a must. 
https://www.chartjs.org/docs/latest/general/performance.html

**Comment by jcmtallon** [comment]
@power-guard 
[Question1] A plant `energy_series` array can contain multiple series in it. Is it guaranteed that the timestamp data will match among all series in the array? Or is it possible that each series could contain different timestamps? 
 
[Question2] In the case we display multiple series in one chart, would you like to be able to identify to which source/solar panel? does each series belong two? In other words, any need to display some sort of identifying label for each series or not at all?

**Comment by power-guard** [comment]
Answer 1:
This will depend on the source data, and so I cannot guarantee it. However, it would be highly unlikely that the timestamps not match up. I think it's safe to assume that they will always match up and if it ever becomes a problem we could deal with it on the back end.

Answer 2:
No, no need at all. If something looks wrong the users have plenty of other tools which they can use to look more deeply into the issue. Not worth the development time either on the front or back.
