### ISSUE TITLE
Question: Server Energy Series Data

### ISSUE THREAD

**Issue by power-guard** [power-guard/pg_monitor_dashboard#19]
Currently, energy series data is set to be provided as a dictionary of timestamps to energy values.
If it's preferable, this could be switched to two arrays or some other representation.
Once you've determined what you will use to render the charts, let me know if a different data representation would make it easier to work with.

**Comment by jcmtallon** [comment]
So far I had no issues creating the charts with the current energy series data structure. 
You can see the implementation details in [this pull request] (https://github.com/power-guard/pg_monitor_dashboard/pull/16).

Please, review the implementation when you have time and we can conttinue debating from there.

**Comment by power-guard** [comment]
Looks good. No change needed, then.
