### ISSUE TITLE
Error handling in case of bad date formatting

### ISSUE THREAD

**Issue by power-guard** [power-guard/pg_monitor_dashboard#24]
It looks like this line throws an unhandled exception if a date is badly formatted. I'm not sure how the page would respond in production. Might be good to add some error handling to make sure the entire page doesn't go down because of a single bad date.

This is a low priority issue.

https://github.com/power-guard/pg_monitor_dashboard/blob/935401ee75b043875ba321c5e8c04611fd04fac5/src/utils/viewUtils.ts#L13

**Comment by jcmtallon** [comment]
Understood. I will add some error handling in here. Thanks for noticing.
