### ISSUE TITLE
Remove point radius from charts

### ISSUE THREAD

**Issue by power-guard** [power-guard/pg_monitor_dashboard#25]
This is personal preference, but I think this would look better with the points hidden.

https://github.com/power-guard/pg_monitor_dashboard/blob/935401ee75b043875ba321c5e8c04611fd04fac5/src/components/EnergySeriesChart.tsx#L31-L32

**Comment by jcmtallon** [comment]
Sure. In fact, I was aiming for the same thing. 

Couldn't find the way to completely remove the points so I initially tried to make them as small as possible. Today I will work on the table styles. I will try to find the way to completely remove them too.
